### ISSUE TITLE
Q：share the checkpoint file and issue with the dataset provided

### ISSUE THREAD

**Issue by bonerush** [shirowalker/UCAD#15]
Could the author share the checkpoint file? Otherwise, the program will throw an error. Additionally, is there an issue with the dataset provided by the author? Most of the PNG images in the dataset appear completely black when I open them.

**Comment by jiaq-liu** [comment]
@bonerush 1. Sorry, I didn't save checkpoints to google drive. Since it is easier to reproduce this code than some other codes, I left the Google Drive space for other projects. Maybe you can check the pytorch version and CUDA>=11.3. Make sure to place the provided dataset in the same folder as the original dataset. 2. It is normal for png images to appear black, because the values ​​in them are relatively low, and they can be read to get the labels of the corresponding blocks, such as 1, 5, 10, etc. Visualizing black does not affect training.
